// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathFinder.Api.Data;

namespace PathFinder.Api.Migrations
{
    [DbContext(typeof(PathFinderContext))]
    [Migration("20200515104036_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PathFinder.Api.Model.PathResult", b =>
                {
                    b.Property<string>("InputArrayString")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsTraversable")
                        .HasColumnType("bit");

                    b.Property<string>("ResultArrayString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InputArrayString");

                    b.ToTable("PathResult");
                });
#pragma warning restore 612, 618
        }
    }
}
